// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.team13.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HouseType_Roo_Configurable {
    
    declare @type: HouseType: @Configurable;
    
}
