// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.team13.domain;

import ee.itcollege.team13.domain.RoomType;
import java.lang.Long;

privileged aspect RoomType_Roo_Entity {
    
    public static RoomType RoomType.findRoomType(Long id) {
        if (id == null) return null;
        return entityManager().find(RoomType.class, id);
    }
    
}
